/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BD.Operaciones;
import Clases.ExistenciaExportar;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.ImageIcon;

/**
 *
 * @author Annie&Teudis
 */
public class ExportarDatos extends javax.swing.JDialog {

    /**
     * Creates new form ExportarDatos
     */
    
    Operaciones op;
    
    ArrayList<ExistenciaExportar> listado_existencia;
    public ExportarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Exportar Datos");
        setIconImage (new ImageIcon(getClass().getResource("/images/icon3.png")).getImage());
        jComboBox1.removeAllItems();
        op =new Operaciones();
        ArrayList<String> semanas = op.get_semanas();
        
        for (int i = 0; i < semanas.size(); i++) {
            
            jComboBox1.addItem(semanas.get(i));
        }
        
       
        
    }
    
    
    public ArrayList get_listado()
    {
     return listado_existencia;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Semana");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Exportar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // Exportar datos de semana
         int semana =  Integer.parseInt(jComboBox1.getSelectedItem().toString());
         listado_existencia =  op.get_existencia_semana(semana);
         // eliminar duplicados
         Set<ExistenciaExportar> limpiar_duplicados = new LinkedHashSet<ExistenciaExportar>();
         limpiar_duplicados.addAll(listado_existencia);
	 listado_existencia.clear();
         listado_existencia.addAll(limpiar_duplicados);
         
         /*
         ArrayList<Integer> listado_eliminar = new ArrayList<>();
         ArrayList<ExistenciaExportar> temp = new ArrayList<>();
         
         // eliminar duplicados
         for (int i = 0; i < listado_existencia.size()-1; i++) {
             for (int j = i+ 1; j < listado_existencia.size(); j++) {
                 if ( listado_existencia.get(i).getAsic_id()== listado_existencia.get(j).getAsic_id() &&
                      listado_existencia.get(i).getTipo_centro_id() == listado_existencia.get(j).getTipo_centro_id() &&
                      listado_existencia.get(i).getProducto_id()==  listado_existencia.get(j).getProducto_id()  &&
                      listado_existencia.get(i).getLote_id()== listado_existencia.get(j).getLote_id() &&
                      listado_existencia.get(i).getServicio_id()== listado_existencia.get(j).getServicio_id() &&
                      listado_existencia.get(i).getFarmacia_id() ==  listado_existencia.get(j).getFarmacia_id() && i!= j  ) {
                     
                     // marcar elementos a eliminar
                     listado_eliminar.add(j);
                     
                 }
                 
                int esta = listado_eliminar.indexOf(j);
                if (esta != -1) {

                    temp.add(listado_existencia.get(i));
                }
                 
             }
             
            
        }
         
        if (temp.size()> 0) {
            
            listado_existencia = temp;
        }
         //System.out.println(listado_existencia.size());
        */
         
         dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExportarDatos dialog = new ExportarDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
