/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BD.Operaciones;
import Clases.Farmacia;
import Clases.Servicios;
import Clases.TipoCentro;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;



/**
 *
 * @author Annie&Teudis
 */
public class SeleccionServicio extends javax.swing.JDialog {

    /**
     * Creates new form SeleccionServicio
     */
    
     Operaciones op ;
     ArrayList<TipoCentro> centros ;
     ArrayList<Servicios> servicios ;
     String [] nombre_servicio;
     ArrayList<Farmacia> f ;
     int [] seleccionados = new int[3] ; 
    public SeleccionServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          //Asigna un titulo a la barra de titulo
        setTitle("Seleccione el servicio");        
        //pone la ventana en el Centro de la pantalla
        setLocationRelativeTo(null);        
       Jcentro.removeAllItems();
       Jservicio.removeAllItems();
       Jfarmacia.removeAllItems();
       //Buscar datos en Base de datos 
        op = new Operaciones();
        f = op.get_farmacias();
       String [] nombre_farmacias = new String[f.size()];
       int [] farmacia_id = new int[f.size()];
       
        for (int i = 0; i < f.size(); i++) {
            
            nombre_farmacias[i] = f.get(i).getNombre();
            farmacia_id[i] = f.get(i).getId();
        }
        
         for (int i = 0; i < nombre_farmacias.length; i++) {
                
              Jfarmacia.addItem(nombre_farmacias[i]);
              
            }
         
         // Llenar  combo centro
          int farmacia_actual = farmacia_id[0];
          centros = op.get_tipo_centros(farmacia_actual);
          int []centros_id = new int[centros.size()];
          String []nombre_centros = new String[centros.size()];
          for (int i = 0; i < centros.size(); i++) {
            
              centros_id[i] = centros.get(i).getId();
              nombre_centros[i] = centros.get(i).getNombre();
              
        }
          
        for (int i = 0; i < nombre_centros.length; i++) {
            
            Jcentro.addItem(nombre_centros[i]);
        }
   
         
        //llenar combo servicios
       int centro_actual = centros_id[0];
       servicios = op.get_servicios(centro_actual);
       nombre_servicio =new String[servicios.size()];
        for (int i = 0; i < servicios.size(); i++) {
            
            nombre_servicio[i] = servicios.get(i).getNombre();
        }
                
        for (int i = 0; i < nombre_servicio.length; i++) {
            
            Jservicio.addItem(nombre_servicio[i]);
            
        }
  
       Jcentro.addItemListener( new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                
                if ( e.getStateChange() == ItemEvent.SELECTED )
               {
                   int pos = Jcentro.getSelectedIndex();
                   
                     servicios = op.get_servicios(centros.get(pos).getId());
                     nombre_servicio =new String[servicios.size()];
                    for (int i = 0; i < servicios.size(); i++) {

                        nombre_servicio[i] = servicios.get(i).getNombre();
                    }
                    
                    Jservicio.removeAllItems();
                    for (int i = 0; i < nombre_servicio.length; i++) {

                        Jservicio.addItem(nombre_servicio[i]);

                    }
                 
               
               }
                
            }
           
       
       });          
               
        
    }
    
    
    public int[] get_datos_seleccionados()
    {
      
    
        return seleccionados;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jcentro = new javax.swing.JComboBox();
        Jservicio = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Jfarmacia = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Tipo de Centro");

        jLabel3.setText("Servicio");

        Jcentro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Jservicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Farmacia");

        Jfarmacia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int farmacia_id = Jfarmacia.getSelectedIndex();
         int centro_id  = Jcentro.getSelectedIndex();
         int servicio_id = Jservicio.getSelectedIndex();         
         farmacia_id = f.get(farmacia_id).getId();
         centro_id = centros.get(centro_id).getId();
         servicio_id = servicios.get(servicio_id).getId();
         seleccionados[0] = farmacia_id;
         seleccionados[1] = centro_id;
         seleccionados[2] = servicio_id;
         dispose();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionServicio dialog = new SeleccionServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Jcentro;
    private javax.swing.JComboBox Jfarmacia;
    private javax.swing.JComboBox Jservicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
